apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oficina-mecanica
resources:
  - ../../base
images:
  - name: oficina-mecanica-api
    newName: 123456789012.dkr.ecr.us-east-1.amazonaws.com/oficina-mecanica-api
    digest: sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
